### User
### Login - Public Route
POST http://localhost:21500/api/user/login
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "email": "email@gmail.com",
  "password": "password"
}

### Register - Public Route
POST http://localhost:21500/api/user/register
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "email": "email@gmail.com",
  "password": "password",
  "username": "password"
}

### Conector
### Get Conectors - Private Route
GET http://localhost:21500/api/conector
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}

### Find Conector By Query - Private Route (query: private)
GET http://localhost:21500/api/conector/private
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}

### Update Conector By id - Private Route (param: id)
### Você pode passar qualquer dado que queira atualizar
### Se for só o nome, passe "name": "novoNome".
PUT http://localhost:21500/api/conector/606749184739eb9bca03764d
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}
Accept: application/json

{
  "type": "REST"
}

### Create Conector - Private Route
POST http://localhost:21500/api/conector
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}
Accept: application/json

{
  "name": "Abner Rodrigues",
  "type": "BD",
  "privacy": "private",
  "base_url": "https://github.com/kingaspx",
  "logo_url": "https://github.com/kingaspx.png",
  "category": "Fullstack",
  "description": "Um dev maneiro e dedicado ;)",
  "status": true
}

### Delete Conector - Private Route
DELETE http://localhost:21500/api/conector/606749184739eb9bca03764d
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}
